# By default, the latest full release (ex: 1.18, as 1.18.2 doesn't have new blocks or items)
# Used for creating new schematics, more info at https://minecraft.fandom.com/wiki/Data_version
mc_version: 2860

# Litematica compatibility version, 5, 6 are supported
# Generally, version 6 only affects scheduled ticks, but parser doesn't support those so don't worry about it
litematica_version: 5

read_only: false
